
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $title ?></title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body ng-app="app" ng-controller="AppController as vm">

<div class="container">

    <h1><?php echo $title ?></h1>
    <p class="lead"><?php echo $description ?></p>

    <h2>Collections</h2>

    <div ng-repeat="collection in vm.documentation.collections" style="box-shadow: 0 0 10px rgba(0,0,0,0.5);">

        <div class="panel panel-primary">
            <div class="panel-heading" style="background: #666" ng-click="collection.hidden=!collection.hidden">
                {{ collection.name ? collection.name : 'Other routes'}}
                <span ng-show="collection.hidden">...</span>
                <span style="float: right" ng-show="collection.hidden">
                    ( {{ collection.endpoints.length }} )
                </span>
            </div>
            <table class="table table-bordered" ng-show="!collection.hidden">
                <tr ng-show="collection.description">
                    <td>{{ collection.description }}</td>
                </tr>
            </table>
            <div class="panel-footer" ng-show="!collection.hidden">

                <div class="panel panel-primary" ng-repeat="endpoint in collection.endpoints">
                    <div class="panel-heading">
                        <span ng-bind-html="endpoint.httpMethod | method"></span> {{ collection.prefix + endpoint.path }}

                        <span style="float: right">{{ endpoint.name }}</span>
                    </div>
                    <table class="table table-bordered">
                        <tr ng-show="endpoint.description">
                            <th>Description</th>
                            <th>{{ endpoint.description }}</th>
                        </tr>
                        <tr>
                            <th style="width: 150px;">Full URL</th>
                            <td>
                                <a ng-href="{{ vm.documentation.basePath + collection.prefix + endpoint.path }}" target="_blank">
                                    {{ vm.documentation.basePath + collection.prefix + endpoint.path }}
                                </a>
                            </td>
                        </tr>
                        <tr ng-show="endpoint.allowedRoles && endpoint.allowedRoles.length">
                            <th style="width: 120px">Allowed roles</th>
                            <td>
                                <div class="label label-primary" ng-repeat="role in endpoint.allowedRoles" style="margin-right: 5px; display: inline-block">{{ role }}</div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <h2 ng-show="vm.documentation.routes && vm.documentation.routes.length">Other routes</h2>

    <div class="panel panel-default" ng-repeat="route in vm.documentation.routes">
        <div class="panel-heading">
            {{ route }}
        </div>
    </div>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script src="https://code.angularjs.org/1.4.8/angular-sanitize.min.js"></script>
<script>
    var documentationPath = './documentation.json';
    var app = angular.module('app', [
        'ngSanitize'
    ]);

    app.controller('AppController', AppController);

    function AppController($http) {

        var vm = this;

        $http.get(documentationPath).then(function(response) {
            vm.documentation = response.data;
        });
    }

    app.filter('method', function() {

        return function(input) {

            switch(input) {
                case 'GET':
                    return '<div class="label label-success">' + input + '</div>';
                case 'POST':
                    return '<div class="label label-warning">' + input + '</div>';
                case 'PUT':
                    return '<div class="label label-info">' + input + '</div>';
                case 'DELETE':
                    return '<div class="label label-danger">' + input + '</div>';
                default:
                    return null;
            }
        }
    });

</script>

</body>
</html>
